# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
identifier = "donate"
name = "Донат"
weight = 2
url = "https://gmod-classix.ru/index.php?t=store"
[main.params]
icon = "cash"
newtab = true

[[social]]
identifier = "vk"
name = "Вконтакте"
weight = 1
url = "https://vk.com/valley_mc"

[social.params]
icon = "brand-vk"

[[social]]
identifier = "telegram"
name = "Telegram"
weight = 2
url = "https://t.me/valley_mc"

[social.params]
icon = "brand-telegram"

[[social]]
identifier = "discord"
name = "Discord"
weight = 3
url = "https://discord.gg/2YR9XQfrZJ"

[social.params]
icon = "brand-discord"
